#!/usr/bin/env zsh
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

"$SCRIPT_DIR/gh-install.sh" \
    "https://github.com/gitleaks/gitleaks/releases/download/v8.16.4/gitleaks_8.16.4_darwin_x64.tar.gz" \
    "4ac90876951f79341a76c61e847394c25895a5c5bbf316453757f7b48651b869" \
    gitleaks
